spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql:///yml?useSSL=false
    username: root
    password: 000000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.jyuyang.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql